//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.25 at 06:49:07 PM CEST 
//


package soap;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RequestString_QNAME = new QName("http://www.ftn.xml/banke", "RequestString");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DownloadRequestDto }
     * 
     */
    public DownloadRequestDto createDownloadRequestDto() {
        return new DownloadRequestDto();
    }

    /**
     * Create an instance of {@link StatusRequestDto }
     * 
     */
    public StatusRequestDto createStatusRequestDto() {
        return new StatusRequestDto();
    }

    /**
     * Create an instance of {@link CSRRequestDto }
     * 
     */
    public CSRRequestDto createCSRRequestDto() {
        return new CSRRequestDto();
    }

    /**
     * Create an instance of {@link RevocationRequestDto }
     * 
     */
    public RevocationRequestDto createRevocationRequestDto() {
        return new RevocationRequestDto();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.xml/banke", name = "RequestString")
    public JAXBElement<String> createRequestString(String value) {
        return new JAXBElement<String>(_RequestString_QNAME, String.class, null, value);
    }

}
