//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.10 at 04:32:27 PM CET 
//


package xml.ftn.banke;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xml.ftn.banke package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xml.ftn.banke
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PosaljiZahtevZaIzvodRequest }
     * 
     */
    public PosaljiZahtevZaIzvodRequest createPosaljiZahtevZaIzvodRequest() {
        return new PosaljiZahtevZaIzvodRequest();
    }

    /**
     * Create an instance of {@link ZahtevZaIzvod }
     * 
     */
    public ZahtevZaIzvod createZahtevZaIzvod() {
        return new ZahtevZaIzvod();
    }

    /**
     * Create an instance of {@link PosaljiNalogZaPlacanjeRequest }
     * 
     */
    public PosaljiNalogZaPlacanjeRequest createPosaljiNalogZaPlacanjeRequest() {
        return new PosaljiNalogZaPlacanjeRequest();
    }

    /**
     * Create an instance of {@link NalogZaPlacanje }
     * 
     */
    public NalogZaPlacanje createNalogZaPlacanje() {
        return new NalogZaPlacanje();
    }

    /**
     * Create an instance of {@link PosaljiZahtevZaIzvodResponse }
     * 
     */
    public PosaljiZahtevZaIzvodResponse createPosaljiZahtevZaIzvodResponse() {
        return new PosaljiZahtevZaIzvodResponse();
    }

    /**
     * Create an instance of {@link Presek }
     * 
     */
    public Presek createPresek() {
        return new Presek();
    }

    /**
     * Create an instance of {@link StavkaPreseka }
     * 
     */
    public StavkaPreseka createStavkaPreseka() {
        return new StavkaPreseka();
    }

    /**
     * Create an instance of {@link Zaglavlje }
     * 
     */
    public Zaglavlje createZaglavlje() {
        return new Zaglavlje();
    }

}
