//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.08 at 12:40:05 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ftn.xml/banke", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package xml.ftn.banke;
