//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.27 at 10:04:54 PM CEST 
//


package xml.ftn.centralnabanka;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xml.ftn.centralnabanka package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Jwt_QNAME = new QName("http://www.ftn.xml/centralnabanka", "jwt");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xml.ftn.centralnabanka
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SendMT103Response }
     * 
     */
    public SendMT103Response createSendMT103Response() {
        return new SendMT103Response();
    }

    /**
     * Create an instance of {@link MT103Response }
     * 
     */
    public MT103Response createMT103Response() {
        return new MT103Response();
    }

    /**
     * Create an instance of {@link SendMT102Response }
     * 
     */
    public SendMT102Response createSendMT102Response() {
        return new SendMT102Response();
    }

    /**
     * Create an instance of {@link MT102Response }
     * 
     */
    public MT102Response createMT102Response() {
        return new MT102Response();
    }

    /**
     * Create an instance of {@link SendMT103Request }
     * 
     */
    public SendMT103Request createSendMT103Request() {
        return new SendMT103Request();
    }

    /**
     * Create an instance of {@link MT103 }
     * 
     */
    public MT103 createMT103() {
        return new MT103();
    }

    /**
     * Create an instance of {@link SendMT102Request }
     * 
     */
    public SendMT102Request createSendMT102Request() {
        return new SendMT102Request();
    }

    /**
     * Create an instance of {@link MT102 }
     * 
     */
    public MT102 createMT102() {
        return new MT102();
    }

    /**
     * Create an instance of {@link MT910 }
     * 
     */
    public MT910 createMT910() {
        return new MT910();
    }

    /**
     * Create an instance of {@link MT900 }
     * 
     */
    public MT900 createMT900() {
        return new MT900();
    }

    /**
     * Create an instance of {@link PojedinacnoPlacanjeMT102 }
     * 
     */
    public PojedinacnoPlacanjeMT102 createPojedinacnoPlacanjeMT102() {
        return new PojedinacnoPlacanjeMT102();
    }

    /**
     * Create an instance of {@link ZaglavljeMT102 }
     * 
     */
    public ZaglavljeMT102 createZaglavljeMT102() {
        return new ZaglavljeMT102();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.xml/centralnabanka", name = "jwt")
    public JAXBElement<String> createJwt(String value) {
        return new JAXBElement<String>(_Jwt_QNAME, String.class, null, value);
    }

}
